<script>
require([
"jquery",
"//cdn-stamped-io.azureedge.net/files/widget.min.js"
], function (jQuery) {

StampedFn.init({
apiKey: '<?php echo $this->getApiKey(); ?>',
storeUrl: '<?php echo $this->getApiStoreUrl(); ?>'
});

})
</script>

<!--
<script>
function initStampedJS(){
  (function e(){var e=document.createElement("script");e.type="text/javascript",e.async=true,e.onload=initStamped,e.src="//cdn-stamped-io.azureedge.net/files/widget.min.js";var t=document.getElementsByTagName("script")[0];t.parentNode.insertBefore(e,t)})();
}

function initStamped(){
}
    
function deferStampedJS(method) {
    if (window.jQuery) {
            initStampedJS();
    } else {
      setTimeout(function() { 
      deferStampedJS(initStampedJS) }, 500);
    }
}
deferStampedJS(initStampedJS);
</script>
-->