<div id="stamped-main-widget" class="stamped stamped-main-widget"
	data-product-id="<?php echo $this->getProductId() ?>"
	data-name="<?php echo $this->getProductName() ?>"
	data-url="<?php echo $this->getProductUrl() ?>"
	data-image-url="<?php echo $this->getProductImageUrl() ?>"
	data-description="<?php echo $this->getProductDescription() ?>"
    data-product-sku="<?php echo $this->getProductSku() ?>">
</div>