<?php
/** @var $block \Stamped\Core\Block\Core */
?>
<span class="stamped-product-reviews-badge"
    data-id="<?= $escaper->escapeHtmlAttr($block->getProductId()) ?>"
    data-product-title="<?= $escaper->escapeHtmlAttr($block->getProductName()) ?>"
    data-url="<?= $escaper->escapeUrl($block->getProductUrl()) ?>"
    data-product-sku="<?= $escaper->escapeHtmlAttr($block->getProductSku()) ?>"
></span>
