<?php
/**
 * @var $block \Stamped\Core\Block\Core
 */
?>
<div id="stamped-main-widget" class="stamped stamped-main-widget"
    data-product-id="<?= $escaper->escapeHtmlAttr($block->getProductId()) ?>"
    data-name="<?= $escaper->escapeHtmlAttr($block->getProductName()) ?>"
    data-url="<?= $escaper->escapeUrl($block->getProductUrl()) ?>"
    data-image-url="<?= $escaper->escapeUrl($block->getProductImageUrl()) ?>"
    data-description="<?= $escaper->escapeHtmlAttr($block->getProductDescription()) ?>"
    data-product-sku="<?= $escaper->escapeHtmlAttr($block->getProductSku()) ?>">
</div>
