<?php
/** @var $block \Stamped\Core\Block\Core */
?>
<?php if ($block->getWidgetShow()):?>
    <div id="stamped-main-widget" class="stamped stamped-main-widget"
        data-product-id="<?= $block->escapeHtmlAttr($block->getProductId()) ?>"
        data-name="<?= $block->escapeHtmlAttr($block->getProductName()) ?>"
        data-url="<?= $block->escapeUrl($block->getProductUrl()) ?>"
        data-image-url="<?= $block->escapeUrl($block->getProductImageUrl()) ?>"
        data-description="<?= $block->escapeHtmlAttr($block->getProductDescription()) ?>"
        data-product-sku="<?= $block->escapeHtmlAttr($block->getProductSku()) ?>">
    </div>
<?php endif ?>
